# Generated by Django 4.2 on 2024-10-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
